### ISSUE TITLE
Failed to run the control channel and the data channel

### ISSUE THREAD

**Issue by ArchGuyWu** [rapiz1/rathole#100]
`Jan 13 12:18:01.913 ERROR new{service=my_ssh}: rathole::client: Failed to run the control channel

Caused by:
    0: Failed to read control cmd
    1: early eof

Retry in 1s...
Jan 13 12:18:01.939 ERROR new{service=my_ssh}:run: rathole::client: Failed to run the data channel

Caused by:
    0: Failed to read data cmd
    1: early eof`
This  was happening all the time since the client started,I don't know why it  happened,but it didn't affect the connection actually,I could still ssh to the computer behind NAT.

**Comment by rapiz1** [comment]
Hi. Thanks for reporting this. However, further information is needed to investigate the issue

Please provide:
- Output of `./rathole --version`
- Full configuration, with sensitive information (IP etc.) masked
- Full log

**Comment by rapiz1** [comment]
BTW, `Failed to run the data channel` indicates unstable network, and is not fatal. `Failed to run the control channel` is fatal and causes the forwarding unusable. These two errors can happen when the server or the client restarts, or network interrupts.

**Comment by ArchGuyWu** [comment]
rathole 
Build Timestamp:     2022-01-08T11:48:49.677820900+00:00
Build Version:       0.3.4
Commit SHA:          Some("1240dd8df93d966e6c357ac67ffcecb6fcf0b1c4")
Commit Date:         Some("2022-01-08T11:39:52+00:00")
Commit Branch:       Some("detached HEAD")
cargo Target Triple: x86_64-pc-windows-msvc
cargo Profile:       release
cargo Features:      base64,client,default,hot_reload,noise,notify,server,snowstorm,tls,tokio_native_tls

clent-side configuration:
[client]
remote_addr = "archguy-rathole-server.xyz:2333" 
[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "Sh/DMjEyzCzd7CTqZlQbK9+aS6RGhlMVZnJSfwBTrU8="
[client.services.my_ssh]
type = "tcp"
token = "WuBo2929470442" 
local_addr = "127.0.0.1:22"

server-side configuration:
[server]
bind_addr = "[::]:2333" # 2333 specifies the port that rathole listens for clients

[server.transport]
type = "noise"
[server.transport.noise]
local_private_key = "vB4TDHu41He1X7Up/SbmMJiiyZSN6UqMHBRyuFGxPOw="
[server.services.my_ssh]
type = "tcp"
token = "WuBo2929470442" 
bind_addr = "[::]:5202" 

I'm sorry,I just forgot to bring the server log:
`Jan 13 04:51:11.932  INFO handle_connection{addr=[2001:da8:c802:232:a44c:d47e:4f6d:1ce1]:8315}: rathole::server: Try to handshake a control channel
Jan 13 04:51:12.033  WARN handle_connection{addr=[2001:da8:c802:232:a44c:d47e:4f6d:1ce1]:8315}: rathole::server: Dropping previous control channel for service my_ssh
Jan 13 04:51:12.033  INFO handle_connection{addr=[2001:da8:c802:232:a44c:d47e:4f6d:1ce1]:8315}: rathole::server: Control channel established service=my_ssh
Jan 13 04:51:12.034  INFO handle_connection{addr=[2001:da8:c802:232:a44c:d47e:4f6d:1ce1]:8305}:new{service=my_ssh}:run{service=my_ssh}: rathole::server: Control channel shutdown
Jan 13 04:51:12.035  INFO handle_connection{addr=[2001:da8:c802:232:a44c:d47e:4f6d:1ce1]:8305}:new{service=my_ssh}:run_tcp_connection_pool: rathole::server: TCPListener shutdown
Jan 13 04:51:12.036  INFO handle_connection{addr=[2001:da8:c802:232:a44c:d47e:4f6d:1ce1]:8305}:new{service=my_ssh}:run_tcp_connection_pool: rathole::server: Shutdown
Jan 13 04:51:12.036  INFO handle_connection{addr=[2001:da8:c802:232:a44c:d47e:4f6d:1ce1]:8315}:new{service=my_ssh}:run_tcp_connection_pool: rathole::server: Listening at [::]:5202`
It seems that the the errors Failed to run the control channel and Failed to run the data channel caused by the failure to handshake in the server-side.

**Comment by rapiz1** [comment]
It's possibly due to unstable network or short TCP keepalive time since you're using mobile data.

I will expose `TCP_KEEPALIVE` setting in the next version and set it a smaller value could solve your issue.

**Comment by ArchGuyWu** [comment]
Thank you a lot,I'll test that again in the next version.

**Comment by rapiz1** [comment]
(v0.3.7)[https://github.com/rapiz1/rathole/releases/tag/v0.3.7] is released

You may adjust the following parameters to decrease the downtime
```
keepalive_secs = 10 # Optional. Specify `tcp_keepalive_time` in `tcp(7)`, if applicable. Default: 10 seconds
keepalive_interval = 5 # Optional. Specify `tcp_keepalive_intvl` in `tcp(7)`, if applicable. Default: 5 seconds
```
