### ISSUE TITLE
Is there a configuration method similar to frp's security exposure intranet service

### ISSUE THREAD

**Issue by whoerau** [rapiz1/rathole#101]
Here is the documentation link

[expose-your-service-privately](https://github.com/fatedier/frp#expose-your-service-privately)
[安全地暴露内网服务](https://gofrp.org/docs/examples/stcp/)

**Comment by rapiz1** [comment]
No. See [Out of Scope](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md). In this case, what you need is a VPN, please consider wireguard
