### ISSUE TITLE
A设备已经和server端进行了连接,B设备如果以和A相同的配置进行连接,会导致A连接不稳定

### ISSUE THREAD

**Issue by justbelieveyourself** [rapiz1/rathole#102]
Caused by:
    0: Failed to read control cmd
    1: early eof

Retry in 1s...
Jan 14 12:37:44.956 ERROR new{service=my_nas_ssh}:run: rathole::client: Failed to run the data channel

**Comment by rapiz1** [comment]
是有定义了同名服务吗？

如果是，这是期望行为。一个service只能有一个来源。两个client同时竞争一个service会导致相互抢占下线。

**Comment by justbelieveyourself** [comment]
是相同的服务名称,可否改成如果A已经进行了连接,B再连接的时候报错,并不对A造成下线的影响

**Comment by rapiz1** [comment]
> 可否改成如果A已经进行了连接,B再连接的时候报错,并不对A造成下线的影响

设计成抢占下线的目的，是希望在原来连接的 Client 僵死的时候，新来的 Client 能够将其快速抢占下线，这样有利于可靠性。

你是想做多活或者负载均衡吗？我推荐你设置多个 service 来避免抢占的问题，让多个 service 同时在线，然后在连接的时候选择其中一个 service 进行连接。

**Comment by justbelieveyourself** [comment]
好的,感谢
想问下server端同时最多可以提供多少个服务,有这方面的测试吗?

**Comment by rapiz1** [comment]
> 想问下server端同时最多可以提供多少个服务

内部使用哈希表存储，没有硬编码上限

> 有这方面的测试吗?

没有这方面的测试，欢迎反馈 :)
