### ISSUE TITLE
Mipsel release not work

### ISSUE THREAD

**Issue by xinxin8816** [rapiz1/rathole#114]
I tried to exec rathole binaries on mipsel device and config it from examples, but it print nothing and usage 25% CPU(100% single thread), looks like be in infinite loop.

CPU is MT7621AT, dual-core with quad-thread.
System is Padavan 3.4.3.9-099_21-10-3, build by hiboyhiboyhiboy.

**Comment by xinxin8816** [comment]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/8501725/150502066-a76d0d6d-000c-41d2-bd77-dc1090db5e70.png">
<img width="241" alt="image" src="https://user-images.githubusercontent.com/8501725/150502114-8a637c7f-af8d-4566-b0d2-b573f05ec447.png">

**Comment by rapiz1** [comment]
Can you test `./rathole --version`?
Or try to produce a binary on yourself? I don't have a mips device so I can't test it for now.

**Comment by xinxin8816** [comment]
`./rathole --version` also not work.
I will try to compile it myself.

**Comment by rapiz1** [comment]
BTW, you may want to disable `tls` feature to make life easier.

A minimal usable binary can be compiled by `cargo build --no-default-features --features client,server`, or `cargo build --no-default-features --features client,server,noise` if you want to have noise support.

**Comment by xinxin8816** [comment]
Unfortunately, cross building success on Windows, but produced binary still on strike.

**Comment by rapiz1** [comment]
It seems that `mipsel-unknown-linux-musl` is just not the right target for many devices. I tried `mipsel-unknown-linux-gnu` and it worked in mipsel qemu. I will make a release containing that very soon.

**Comment by rapiz1** [comment]
[rathole-mipsel-gnu.zip](https://github.com/rapiz1/rathole/files/7914099/rathole-mipsel-gnu.zip)
Can you try this out?

**Comment by xinxin8816** [comment]
Not good. 
Perhaps lossed some lib, because of Padavan and OpenWrt is the lightweighting system.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/8501725/150539631-45245cb0-d2c4-4f9a-b434-10b2d9523a2c.png">

**Comment by rapiz1** [comment]
> Not good.
Perhaps lossed some lib, because of Padavan and OpenWrt is the lightweighting system.

Yes. This is possibly caused by an old glibc version.

[rathole-musl-release.zip](https://github.com/rapiz1/rathole/files/7914216/rathole-musl-release.zip) This can work if you have muslc installed. I don't know if it comes with Padavan... But maybe you can have a try.

**Comment by xinxin8816** [comment]
After I copied `libc.so` `libgcc_s.so.1` `ld-musl-*` from OpenWrt 21.02 project to my device, all of above mentioned releases are starting working now.

**Comment by xinxin8816** [comment]
I will close issue then as I think we have a workaround.

**Comment by rapiz1** [comment]
> After I copied libc.so libgcc_s.so.1 ld-musl-* from OpenWrt 21.02 project to my device, all of above mentioned releases are starting working now.

Great.

Just for the sake of someone who happened to read this, overriding glibc is dangerous. Only do this when you know what you're doing.

**Comment by rapiz1** [comment]
Release v0.3.9 is out and contains fixed binaries

**Comment by vcheckzen** [comment]
> Release v0.3.9 is out and contains fixed binaries

It still doesn't work on my openwrt mt7621 device, I've tried all the mips binaries. Here is some system info

```shell
# uname -a
Linux LOGI 3.14.79 #0 SMP Fri Feb 1 20:24:57 2019 mips PandoraBox

# find / -name libc*
/lib/libc.so.0
/lib/libc.so.1
/lib/libcrypt.so.0
/lib/libcrypt.so.1
/overlay/usr/lib/opkg/info/libcurl.postinst
/overlay/usr/lib/opkg/info/libcurl.list
/overlay/usr/lib/opkg/info/libcurl.control
/overlay/usr/lib/opkg/info/libcurl.prerm
/overlay/usr/lib/libcurl.so.4
/overlay/usr/lib/libcurl.so.4.4.0
/rom/lib/libc.so.0
/rom/lib/libc.so.1
/rom/lib/libcrypt.so.0
/rom/lib/libcrypt.so.1
/rom/usr/lib/libcrypto.so.1.0.0
/rom/usr/lib/opkg/info/libc.control
/rom/usr/lib/opkg/info/libc.list
/usr/lib/libcrypto.so.1.0.0
/usr/lib/opkg/info/libc.control
/usr/lib/opkg/info/libc.list
/usr/lib/opkg/info/libcurl.postinst
/usr/lib/opkg/info/libcurl.list
/usr/lib/opkg/info/libcurl.control
/usr/lib/opkg/info/libcurl.prerm
/usr/lib/libcurl.so.4
/usr/lib/libcurl.so.4.4.0

# cat /proc/cpuinfo
system type             : MediaTek MT7621
machine                 : Phicomm K2P
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 2
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 3
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 583.68
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by rapiz1** [comment]
@vcheckzen That's also caused by incompatible libc. Can you provide your libc version?

It's not easy to provide binaries for all possible distributions. I'm looking into statically linking solution and OpenWrt SDK to solve the issue for good.

**Comment by vcheckzen** [comment]
> @vcheckzen That's also caused by incompatible libc. Can you provide your libc version?
> 
> It's not easy to provide binaries for all possible distributions. I'm looking into statically linking solution and OpenWrt SDK to solve the issue for good.

```shell
[root@LOGI:/root]#ll /lib/*libc*
-rwxr-xr-x    1 root     root       28.3K Feb  2  2019 /lib/ld-uClibc-1.0.31.so
lrwxrwxrwx    1 root     root          14 Feb  2  2019 /lib/ld-uClibc.so.0 -> ld-uClibc.so.1
lrwxrwxrwx    1 root     root          19 Feb  2  2019 /lib/ld-uClibc.so.1 -> ld-uClibc-1.0.31.so
lrwxrwxrwx    1 root     root          19 Feb  2  2019 /lib/libc.so.0 -> libuClibc-1.0.31.so
lrwxrwxrwx    1 root     root          19 Feb  2  2019 /lib/libc.so.1 -> libuClibc-1.0.31.so
lrwxrwxrwx    1 root     root          19 Feb  2  2019 /lib/libcrypt.so.0 -> libuClibc-1.0.31.so
lrwxrwxrwx    1 root     root          19 Feb  2  2019 /lib/libcrypt.so.1 -> libuClibc-1.0.31.so
-rwxr-xr-x    1 root     root      600.7K Feb  2  2019 /lib/libuClibc-1.0.31.so
```

And the toolchain is here

http://downloads.pangubox.com:6380/pandorabox/19.02/targets/ralink/mt7621/

**Comment by sparkssssssss** [comment]
> I tried to exec rathole binaries on mipsel device and config it from examples, but it print nothing and usage 25% CPU(100% single thread), looks like be in infinite loop.
> 
> CPU is MT7621AT, dual-core with quad-thread. System is Padavan 3.4.3.9-099_21-10-3, build by hiboyhiboyhiboy.

老铁，我也是用的hiboy的老毛子，能否分享下你的可用的版本和lib啊？我找了一些so但是始终无法正常启动，多谢了

**Comment by xinxin8816** [comment]
我已经不用老毛子了，相关的库也没留存

sparkssssssss ***@***.***> 于2026年1月21日周三 09:52写道：

**Comment by sparkssssssss** [comment]
[rathole-mt7621.zip](https://github.com/user-attachments/files/25249448/rathole-mt7621.zip)

分析个自己静态编译的，在我的k2p的老毛子上，可以正常使用

**Comment by WhitespaceQ** [comment]
What version are you compiling against? dev-latest or main?
