### ISSUE TITLE
client端部署在路由器上,路由器断网重连之后,client连接上了server端之后一会,出现了shutdown的情况

### ISSUE THREAD

**Issue by justbelieveyourself** [rapiz1/rathole#116]
如图所示
![image](https://user-images.githubusercontent.com/20918585/150719830-f897961b-3c93-492a-aab0-8ce95ce8f62e.png)

**Comment by rapiz1** [comment]
网络中断或波动后出现 shutdown 是正常的。自动重连是否工作正常？

**Comment by rapiz1** [comment]
`Config watcher exiting` 退出是反常的。一般 Ctrl+C 终止程序才会让 Config Watcher 退出进而使整个程序退出

**Comment by justbelieveyourself** [comment]
在这之后能用了一会,然后就停止了,我是用nohup启动的,没有执行Ctrl+C

**Comment by rapiz1** [comment]
根据你截图最上面的日志格式，我想你使用的应该不是最新版本？如果你可以提供在最新版(目前是v0.3.9)上大概率复现问题的步骤，我方便能够帮助排查和解决。

**Comment by rapiz1** [comment]
https://github.com/rapiz1/rathole/issues/117

**Comment by moxuanyuan** [comment]
> 根据你截图最上面的日志格式，我想你使用的应该不是最新版本？如果你可以提供在最新版(目前是v0.3.9)上大概率复现问题的步骤，我方便能够帮助排查和解决。

我使用 0.4.0 版，存在同样的问题，路由器每天定时断网重连后，client 与 server 端就连不上，重启 client 或者 server 就行，请问应该怎样处理？
