### ISSUE TITLE
Systemd README 内容与单元文件不一致

### ISSUE THREAD

**Issue by Sec-ant** [rapiz1/rathole#118]
提个小问题

[README](https://github.com/rapiz1/rathole/blob/main/examples/systemd/README.md) 中写的是：

> Assuming that `rathole` is installed in `/usr/local/bin/rathole`,

给出的几个单元文件里面的配置是：

> ```ini
> ExecStart=/usr/bin/rathole /etc/rathole/%i.toml
> ```

rathole 路径不一致，可能是作者笔误，希望能改一下 :D

**Comment by rapiz1** [comment]
感谢你指出这一点！已修改。
