### ISSUE TITLE
There are many error with the rathole server

### ISSUE THREAD

**Issue by justbelieveyourself** [rapiz1/rathole#130]
Feb 11 09:21:27.470 ERROR connection{addr=83.97.20.34:2979}: rathole::server: Failed to deserialize hello: invalid value: integer `542393671`, expected variant index 0 <= i < 2
Feb 11 09:21:38.000 ERROR connection{addr=83.97.20.34:15795}: rathole::server: Failed to read hello: early eof
Feb 11 09:21:38.233 ERROR connection{addr=83.97.20.34:52051}: rathole::server: Failed to deserialize hello: invalid value: integer `671088768`, expected variant index 0 <= i < 2
Feb 11 09:21:48.731 ERROR connection{addr=83.97.20.34:3996}: rathole::server: Failed to read hello: early eof
Feb 11 10:27:36.946 ERROR connection{addr=101.133.138.230:51670}: rathole::server: Failed to deserialize hello: invalid value: integer `671088768`, expected variant index 0 <= i < 2
Feb 11 10:27:47.350 ERROR connection{addr=101.133.138.230:55432}: rathole::server: Failed to read hello: early eof
Feb 11 10:27:49.353 ERROR connection{addr=101.133.138.230:57132}: rathole::server: Failed to deserialize hello: invalid value: integer `790`, expected variant index 0 <= i < 2
Feb 11 10:28:00.770 ERROR connection{addr=101.133.138.230:58620}: rathole::server: Failed to read hello: early eof
Feb 11 10:28:08.375 ERROR connection{addr=101.133.138.230:60570}: rathole::server: Failed to read hello: early eof
Feb 11 10:28:17.586 ERROR connection{addr=101.133.138.230:34172}: rathole::server: Failed to read hello: early eof
Feb 11 10:28:24.797 ERROR connection{addr=101.133.138.230:36562}: rathole::server: Failed to read hello: early eof
Feb 11 10:28:32.612 ERROR connection{addr=101.133.138.230:37898}: rathole::server: Failed to read hello: early eof
Feb 11 10:28:41.416 ERROR connection{addr=101.133.138.230:39446}: rathole::server: Failed to read hello: early eof
Feb 11 10:28:53.035 ERROR connection{addr=101.133.138.230:41160}: rathole::server: Failed to read hello: early eof
Feb 11 10:29:03.247 ERROR connection{addr=101.133.138.230:43514}: rathole::server: Failed to read hello: early eof
Feb 11 10:29:04.442 ERROR connection{addr=101.133.138.230:46090}: rathole::server: Failed to deserialize hello: invalid value: integer `704643075`, expected variant index 0 <= i < 2
Feb 11 10:29:07.852 ERROR connection{addr=101.133.138.230:46658}: rathole::server: Failed to deserialize hello: invalid value: integer `790`, expected variant index 0 <= i < 2
Feb 11 10:29:12.251 ERROR connection{addr=101.133.138.230:47316}: rathole::server: Failed to deserialize hello: invalid value: integer `50437760`, expected variant index 0 <= i < 2
Feb 11 10:29:16.456 ERROR connection{addr=101.133.138.230:48110}: rathole::server: Failed to deserialize hello: invalid value: integer `1895825408`, expected variant index 0 <= i < 2
Feb 11 10:29:20.465 ERROR connection{addr=101.133.138.230:48976}: rathole::server: Failed to deserialize hello: invalid value: integer `2751463424`, expected variant index 0 <= i < 2
Feb 11 10:29:25.466 ERROR connection{addr=101.133.138.230:50494}: rathole::server: Failed to deserialize hello: invalid value: integer `542393671`, expected variant index 0 <= i < 2
Feb 11 10:29:36.675 ERROR connection{addr=101.133.138.230:51372}: rathole::server: Failed to read hello: early eof
Feb 11 10:29:38.879 ERROR connection{addr=101.133.138.230:53168}: rathole::server: Failed to deserialize hello: invalid value: integer `33840`, expected variant index 0 <= i < 2
Feb 11 10:29:48.489 ERROR connection{addr=101.133.138.230:54228}: rathole::server: Failed to read hello: early eof
Feb 11 10:29:50.492 ERROR connection{addr=101.133.138.230:55526}: rathole::server: Failed to deserialize hello: invalid value: integer `1230262351`, expected variant index 0 <= i < 2
Feb 11 10:30:00.701 ERROR connection{addr=101.133.138.230:56574}: rathole::server: Failed to read hello: early eof
Feb 11 10:30:08.108 ERROR connection{addr=101.133.138.230:58180}: rathole::server: Failed to read hello: early eof
Feb 11 10:30:16.116 ERROR connection{addr=101.133.138.230:59720}: rathole::server: Failed to read hello: early eof
Feb 11 10:30:18.719 ERROR connection{addr=101.133.138.230:33068}: rathole::server: Failed to deserialize hello: invalid value: integer `58`, expected variant index 0 <= i < 2
Feb 11 10:30:22.922 ERROR connection{addr=101.133.138.230:33900}: rathole::server: Failed to deserialize hello: invalid value: integer `1414744388`, expected variant index 0 <= i < 2
Feb 11 10:30:31.731 ERROR connection{addr=101.133.138.230:34598}: rathole::server: Failed to read hello: early eof
Feb 11 10:30:38.138 ERROR connection{addr=101.133.138.230:35698}: rathole::server: Failed to read hello: early eof
Feb 11 10:30:45.746 ERROR connection{addr=101.133.138.230:37108}: rathole::server: Failed to read hello: early eof
Feb 11 10:30:47.148 ERROR connection{addr=101.133.138.230:38314}: rathole::server: Failed to deserialize hello: invalid value: integer `4244635649`, expected variant index 0 <= i < 2
Feb 11 10:30:51.553 ERROR connection{addr=101.133.138.230:38892}: rathole::server: Failed to deserialize hello: invalid value: integer `23040`, expected variant index 0 <= i < 2
Feb 11 10:31:06.777 ERROR connection{addr=101.133.138.230:39534}: rathole::server: Failed to read hello: early eof
Feb 11 10:31:13.778 ERROR connection{addr=101.133.138.230:42300}: rathole::server: Failed to read hello: early eof
Feb 11 10:31:16.180 ERROR connection{addr=101.133.138.230:43568}: rathole::server: Failed to deserialize hello: invalid value: integer `16778245`, expected variant index 0 <= i < 2
Feb 11 10:31:25.390 ERROR connection{addr=101.133.138.230:44310}: rathole::server: Failed to read hello: early eof
Feb 11 10:31:27.792 ERROR connection{addr=101.133.138.230:45870}: rathole::server: Failed to deserialize hello: invalid value: integer `872415506`, expected variant index 0 <= i < 2
Feb 11 10:31:38.002 ERROR connection{addr=101.133.138.230:46588}: rathole::server: Failed to read hello: early eof
Feb 11 10:31:45.409 ERROR connection{addr=101.133.138.230:47950}: rathole::server: Failed to read hello: early eof
Feb 11 10:31:48.013 ERROR connection{addr=101.133.138.230:49270}: rathole::server: Failed to deserialize hello: invalid value: integer `16777216`, expected variant index 0 <= i < 2
Feb 11 10:31:51.816 ERROR connection{addr=101.133.138.230:49972}: rathole::server: Protocol version mismatched. Expected 0, got 68. Please update `rathole`.
Feb 11 10:31:56.019 ERROR connection{addr=101.133.138.230:50654}: rathole::server: Failed to deserialize hello: invalid value: integer `49665`, expected variant index 0 <= i < 2
Feb 11 10:32:00.632 ERROR connection{addr=101.133.138.230:51682}: rathole::server: Failed to deserialize hello: invalid value: integer `1701407811`, expected variant index 0 <= i < 2
Feb 11 10:32:05.430 ERROR connection{addr=101.133.138.230:52596}: rathole::server: Failed to deserialize hello: invalid value: integer `4915260`, expected variant index 0 <= i < 2
Feb 11 10:32:15.239 ERROR connection{addr=101.133.138.230:53196}: rathole::server: Failed to read hello: early eof
Feb 11 10:32:23.447 ERROR connection{addr=101.133.138.230:54858}: rathole::server: Failed to read hello: early eof
Feb 11 10:32:32.256 ERROR connection{addr=101.133.138.230:56468}: rathole::server: Failed to read hello: early eof
Feb 11 10:32:33.858 ERROR connection{addr=101.133.138.230:58462}: rathole::server: Failed to deserialize hello: invalid value: integer `3857049026`, expected variant index 0 <= i < 2
Feb 11 10:32:44.067 ERROR connection{addr=101.133.138.230:59288}: rathole::server: Failed to read hello: early eof
Feb 11 10:32:46.470 ERROR connection{addr=101.133.138.230:32932}: rathole::server: Failed to deserialize hello: invalid value: integer `1006736384`, expected variant index 0 <= i < 2
Feb 11 10:32:49.273 ERROR connection{addr=101.133.138.230:33726}: rathole::server: Failed to deserialize hello: invalid value: integer `30421504`, expected variant index 0 <= i < 2
Feb 11 10:32:52.879 ERROR connection{addr=101.133.138.230:34568}: rathole::server: Failed to deserialize hello: invalid value: integer `541610836`, expected variant index 0 <= i < 2
Feb 11 10:32:56.281 ERROR connection{addr=101.133.138.230:35510}: rathole::server: Failed to deserialize hello: invalid value: integer `542393671`, expected variant index 0 <= i < 2
Feb 11 10:33:00.486 ERROR connection{addr=101.133.138.230:36266}: rathole::server: Failed to deserialize hello: invalid value: integer `65`, expected variant index 0 <= i < 2
Feb 11 10:33:09.697 ERROR connection{addr=101.133.138.230:37022}: rathole::server: Failed to read hello: early eof
Feb 11 10:33:17.104 ERROR connection{addr=101.133.138.230:38342}: rathole::server: Failed to read hello: early eof
Feb 11 10:33:23.113 ERROR connection{addr=101.133.138.230:40324}: rathole::server: Failed to read hello: early eof
Feb 11 10:33:30.519 ERROR connection{addr=101.133.138.230:41560}: rathole::server: Failed to read hello: early eof
Feb 11 10:33:38.128 ERROR connection{addr=101.133.138.230:42914}: rathole::server: Failed to read hello: early eof
Feb 11 10:33:46.543 ERROR connection{addr=101.133.138.230:44886}: rathole::server: Failed to read hello: early eof
Feb 11 10:33:53.346 ERROR connection{addr=101.133.138.230:46926}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:00.153 ERROR connection{addr=101.133.138.230:48628}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:07.367 ERROR connection{addr=101.133.138.230:50016}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:15.373 ERROR connection{addr=101.133.138.230:51504}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:22.394 ERROR connection{addr=101.133.138.230:53432}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:23.189 ERROR connection{addr=101.133.138.230:54876}: rathole::server: Failed to deserialize hello: invalid value: integer `1347373383`, expected variant index 0 <= i < 2
Feb 11 10:34:30.014 ERROR connection{addr=101.133.138.230:55302}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:35.425 ERROR connection{addr=101.133.138.230:56638}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:41.040 ERROR connection{addr=101.133.138.230:57638}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:46.850 ERROR connection{addr=101.133.138.230:58858}: rathole::server: Failed to read hello: early eof
Feb 11 10:34:52.278 ERROR connection{addr=101.133.138.230:60084}: rathole::server: Failed to read hello: early eof
Feb 11 10:40:24.480 ERROR connection{addr=101.133.138.230:36676}: rathole::server: Failed to read hello: early eof
Feb 11 10:40:24.509 ERROR connection{addr=101.133.138.230:38644}: rathole::server: Failed to deserialize hello: invalid value: integer `33620758`, expected variant index 0 <= i < 2
Feb 11 10:40:54.505 ERROR connection{addr=101.133.138.230:792}: rathole::server: Failed to deserialize hello: invalid value: integer `671088768`, expected variant index 0 <= i < 2
Feb 11 10:56:57.746 ERROR connection{addr=89.248.165.32:48202}: rathole::server: Failed to read hello: Connection reset by peer (os error 104)
Feb 11 10:57:10.888 ERROR connection{addr=89.248.165.32:48058}: rathole::server: Failed to read hello: early eof
Feb 11 11:20:18.260 ERROR connection{addr=185.219.52.154:62512}: rathole::server: Failed to read hello: Connection reset by peer (os error 104)
Feb 11 11:24:14.834 ERROR connection{addr=185.219.52.154:63043}: rathole::server: Failed to deserialize hello: invalid value: integer `1577058578`, expected variant index 0 <= i < 2
Feb 11 12:09:25.509 ERROR connection{addr=89.248.163.202:50358}: rathole::server: Failed to read hello: early eof

**Comment by rapiz1** [comment]
Please follow the bug report template to provide the necessary information for debugging.
