### ISSUE TITLE
wsl2 ubuntu 20.04

### ISSUE THREAD

**Issue by kongdd** [rapiz1/rathole#132]
Hi @rapiz1, 

我在使用wsl2 ubuntu 20.04:
```bash
uname -a
Linux kong-dell 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
但是从release下载的文件，尝试了6/7个版本，均不能正常运行，报相同的问题：`exec format error:`.
请问rathole在ubuntu 64位系统中应该用哪个版本的文件？

感谢

**Comment by rapiz1** [comment]
[rathole-x86_64-unknown-linux-musl.zip](https://github.com/rapiz1/rathole/releases/download/v0.3.9/rathole-x86_64-unknown-linux-musl.zip)

**Comment by kongdd** [comment]
Thank u. works.
