### ISSUE TITLE
wish to support websocket transport

### ISSUE THREAD

**Issue by aa51513** [rapiz1/rathole#134]
websocket has been widely used and supported by attack prevention providers such as cloudflare

 And I noticed that Rust already supports Websocket dependencies and can be used directly 

Could you consider adding support for the websocket protocol in the transport type?

**Comment by 9p4** [comment]
Websocket seems to work just fine for me (TCP)

**Comment by tyleraharrison** [comment]
Working for me as well

**Comment by remram44** [comment]
I have the same request, and I'm confused by the comments. This is a request for WebSocket *transport*, not services, and is not implemented. I cannot be "working for you".

**Comment by rucciva** [comment]
Would be awesome if rathole support this. My use case is to expose a port of an internal service running inside kubernetes to another kubernetes cluster. Being able to expose rathole server through ingress would prevent opening another tcp port and reducing attack surface.

**Comment by tyleraharrison** [comment]
> I have the same request, and I'm confused by the comments. This is a request for WebSocket _transport_, not services, and is not implemented. It cannot be "working for you".

Ahh I misunderstood, this makes more sense.

**Comment by rucciva** [comment]
Hi @rapiz1 , will PR accepted for this. I have no rust background but i'm willing to learn. I've read about tokio-tungstenite as possible library, wdyt?

**Comment by rucciva** [comment]
i tried to make a websocket transport using tokio-tungstenite [here](https://github.com/TelkomIndonesia/rathole/blob/main/src/transport/websocket.rs)

It passes the tcp test but unfortunately the udp test stuck. i'm not sure why. 

maybe anyone here got a clue?

**Comment by rucciva** [comment]
Hi @aa51513 & @remram44 , would you care to try it?

there is a downloadable executable in <https://github.com/rapiz1/rathole/actions/runs/6308179808> and sample config in:
- <https://github.com/TelkomIndonesia/rathole/blob/main/tests/for_tcp/websocket_transport.toml>
- <https://github.com/TelkomIndonesia/rathole/blob/main/tests/for_tcp/websocket_secure_transport.toml>
- <https://github.com/TelkomIndonesia/rathole/blob/main/tests/for_udp/websocket_transport.toml>
- <https://github.com/TelkomIndonesia/rathole/blob/main/tests/for_udp/websocket_secure_transport.toml>
