### ISSUE TITLE
Proxy protocol support

### ISSUE THREAD

**Issue by Shonke** [rapiz1/rathole#142]
Proxy protocol allows internal services to obtain remote ip.
https://nginx.org/en/docs/http/ngx_http_core_module.html#listen
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

It should be this:
```
[client.services.service1]
local_addr = "127.0.0.1:1082"
proxy_protocol = true
```

**Comment by rapiz1** [comment]
You can use nginx as a gateway in front of rathole to achieve this. rathole doesn't interface with the application layer protocol.

In the future, this may be added as a feature along with the web dashboard.
