### ISSUE TITLE
client 断线后能否自动重连？

### ISSUE THREAD

**Issue by moxuanyuan** [rapiz1/rathole#145]
之前发过 issue https://github.com/rapiz1/rathole/issues/143

### 问题一
路由定时重启断线后，client 端不会自动重连 ，显示 “ Operation timed out (os error 110)” 

### 问题二
每天总会有连不上海外 server 端的情况（国内线路问题），client 端一样会出现 “ Operation timed out (os error 110)” 的问题

第一个问题，因为路由器是定时重启，所以我可以设个 crontab 自动 restart client 端。

但第二个问题，因为线路不能访问的情况是不可控。。我没法预知什么时间连不上，连不上时间多久。。

所以，有没有办法，可以设置 client 在断线后，自动检测，自动重连？

**Comment by rapiz1** [comment]
Should be fixed in v0.4.1
