### ISSUE TITLE
获取真实IP

### ISSUE THREAD

**Issue by vopo** [rapiz1/rathole#150]
你好，偿试从 frp 迁移 rathole 过程中，遇到问题，向作者请教：

类似 frpc.ini 中配置参数 proxy_protocol_version = v2

**Comment by rapiz1** [comment]
Server前放一个nginx，设置xforwardedfor



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月8日(周五) 晚上7:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [rapiz1/rathole] 获取真实IP (Issue #150)




 
你好，偿试从 frp 迁移 rathole 过程中，遇到问题，向作者请教：
 
rathole-server(80,443)
 ↓
 rathole-client
 ↓
 nginx(X-Real-IP,X-Forwarded-For)  ← 是否有机制，以便获取用户真实IP
