### ISSUE TITLE
rathole 是否有支持windows2003的版本?

### ISSUE THREAD

**Issue by snoopy33383622** [rapiz1/rathole#172]
下载了v0.4.2  rathole-x86_64-pc-windows-msvc.zip  ，在windows2003上报，不是有效的win32程序。

**Comment by rapiz1** [comment]
这个提示是字长（32位 vs 64位）的问题。暂时没有尝试过编译x86 32位版本



---Original---
From: ***@***.***&gt;
Sent at: 2022年7月31日(Sun) Early Morning2:47
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] rathole 是否有支持windows2003的版本? (Issue #172)




 
下载了v0.4.2  rathole-x86_64-pc-windows-msvc.zip  ，在windows2003上报，不是有效的win32程序。

**Comment by snoopy33383622** [comment]
肯定会支持的，用32版本



---原始邮件---
发件人: "Yujia ***@***.***&gt;
发送时间: 2023年10月1日(周日) 晚上6:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [rapiz1/rathole] rathole 是否有支持windows2003的版本? (Issue #172)




 
Closed #172 as not planned.
