### ISSUE TITLE
external IP forward

### ISSUE THREAD

**Issue by lootoos** [rapiz1/rathole#175]
The rathole server will take the external IP of the connected player and transfer it to the rathole client so that the players have the correct IP on the Minecraft game server
 

  The function will be useful for game servers\sites

**Comment by rapiz1** [comment]
Not possible. You need application specific protocol for that

**Comment by lootoos** [comment]
but why is bungecord able to do Ip forward via the wireguard network?

**Comment by rapiz1** [comment]
Because bungeecord is specifically designed for Minecraft and tell it IPs in some way. It really depends on how MC works and interoperate with it. It's not possible because the layer that rathole works doesn't know anything about MC.

**Comment by rapiz1** [comment]
I don't know about MC servers nowadays. But it's possible what you asked for can be done in a alternative way.

For example, in the case of HTTP, if the web server wants to see the real source address, a haproxy will be needed in front of rathole server and set corresponding proxy header. And that header is HTTP specific.

Maybe something similar could be done for your case

**Comment by lootoos** [comment]
is it possible to do the same for the Udp protocol? I read that HAProxy does not support UDP

**Comment by rapiz1** [comment]
They're different layers. You can't get the real source address from TCP or UDP. It's only possible with the upper layer e.g. HTTP. 

You need to learn about what's TCP, UDP and what the protocol of MC provides to properly set up.
