### ISSUE TITLE
通过泛域名解析来管理物联网设备

### ISSUE THREAD

**Issue by zsinba** [rapiz1/rathole#179]
**Feature Proposed**

目前使用FRP做的物联网设备管理.
使用泛域名解析的方式:
*.device.abc.com 指向某ip地址;
所有设备通过设备ID上线:
D001.device.abc.com;
D002.device.abc.com
D003.device.abc.com
D004.device.abc.com

需要连接 某设备时,使用DXXXdevice.abc.com可以连接过去 .
设备上线时,仅需要配置设备端,通过规则(设备ID+指定后缀)可访问到设备.

目前Rathole是通过端口的方式转发映射,假设有1000个设备,就需要1000个端口对应起来,同时 Rathole目前没有APi的功能.

如果管理N个设备,就需要通过N个设备的端口来访问,这不是不可以. 但是如果可以通过泛域名的方式来解决,或者可以很方便.

看到Rathole里说到不做nginx的一些功能,但是这并不算Nginx的功能. 通过泛域名解析,可以给Rathole赋予更大的使命.

目前我能想到的办法:
Rathole通过端口映射了N个设备;
Nginx通过泛域名访问到不同端口(LUNA也不是太麻烦 )
这倒是可实现目前的需求. 有些曲折.

**Use Case**

**Comment by zsinba** [comment]
有什么建议吗？

**Comment by HollisMeynell** [comment]
这完全是nginx的反向代理功能
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
这是一段示例:
`
server {
        listen 80;
        server_name D001.device.abc.com;
        location / {
            proxy_pass http://127.0.0.1:9000;
        }
    }
`

**Comment by zsinba** [comment]
> 这完全是nginx的反向代理功能 https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/ 这是一段示例: `server { listen 80; server_name D001.device.abc.com; location / { proxy_pass http://127.0.0.1:9000; } }`

这样不是不可以，只是有些曲折。

**Comment by HollisMeynell** [comment]
https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md
开发者已经在此说明了，不会支持这种功能的

**Comment by zsinba** [comment]
> https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md 开发者已经在此说明了，不会支持这种功能的

看到说明了， 所以请教下作者有什么建议。

**Comment by zsinba** [comment]
Rathole很大的优势是体积小， 性能强。 用在低配的物联网设备上，比FRP有优势（可能），但是，每个设备映射一个端口出来，这又是很大的劣势了。
所以，希望作者可以考虑下这种优势 + 场景的合并，怎样做能更加高效的推广应用。


@HollisMeynell  感谢你的回复。

**Comment by rapiz1** [comment]
> 同时 Rathole目前没有APi的功能.

目前是这样的，但是已经有了配置热重载。也就是说可以生成配置文件来达成这个目的。当然这不是最优解。这几个月有些忙，接下来我会重点进行 API 的开发。

> 目前Rathole是通过端口的方式转发映射

rathole 没有工作在应用层（HTTP层）的打算，一开始也没有相关设计。需要HTTP层时，推荐的用法仍然是搭配非常成熟的 nginx。
