### ISSUE TITLE
tls传输用不了

### ISSUE THREAD

**Issue by csdfsdffese** [rapiz1/rathole#180]
tls传输使用自签证书后所有配置都对的情况下，且无报错，但是用不了

**Comment by rapiz1** [comment]
如果你不提供相关配置来帮助复现，我什么都做不了。每个commit都会被ci测试tls功能的可用性。



---Original---
From: ***@***.***&gt;
Sent at: 2022年8月12日(Fri) PM5:05
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] tls传输用不了 (Issue #180)




 
tls传输使用自签证书后所有配置都对的情况下，且无报错，但是用不了
