### ISSUE TITLE
希望增加一个内置代理

### ISSUE THREAD

**Issue by shijunti19** [rapiz1/rathole#182]
因为网络在封闭环境，遇到了需要通过代理才可以访问外网的问题
希望增加一个内置代理的功能，大部分软件都有这个功能

**Comment by rapiz1** [comment]
已经支持socks代理的了



---Original---
From: ***@***.***&gt;
Sent at: 2022年8月26日(Fri) AM10:24
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] 希望增加一个内置代理 (Issue #182)




 
因为网络在封闭环境，遇到了需要通过代理才可以访问外网的问题
 希望增加一个内置代理的功能，大部分软件都有这个功能

**Comment by shijunti19** [comment]
@rapiz1 
nodelay = false # Optional. Determine whether to enable TCP_NODELAY, if applicable, to improve the latency but decrease the bandwidth. Default: false
keepalive_secs = 20 # Optional. Specify `tcp_keepalive_time` in `tcp(7)`, if applicable. Default: 20 seconds
keepalive_interval = 8 # Optional. Specify `tcp_keepalive_intvl` in `tcp(7)`, if applicable. Default: 8 seconds

可不可以中文解释下这几个参数的意思
我现在遇到这样的问题，代理后，如果长时间不连接，请求会失败，我不停刷新好几遍他又恢复正常了，我需要他一直保持链接，每次访问都可以！

**Comment by shijunti19** [comment]
我测试下来
[client.transport.tcp]
#proxy = "http://127.0.0.1:808"
#proxy = "socks5://127.0.0.1:1080"
2个都失败，但是
![image](https://user-images.githubusercontent.com/5392211/187225511-5f104aea-4804-43b4-97d4-c57a91889ef6.png)
这个就可以正常链接，很奇怪，内置的不支持代理
