### ISSUE TITLE
plugin_socks5 wanted

### ISSUE THREAD

**Issue by stainboy** [rapiz1/rathole#188]
**Feature Proposed**
Thank you for building such a great tool so far, which I like very much! How about bringing `frp` `plugin_socks5` like feature into `rathole`?

Refer https://github.com/fatedier/frp/blob/dev/conf/frpc_full.ini#L260
```
[plugin_socks5]
type = tcp
remote_port = 6005
plugin = socks5
plugin_user = abc
plugin_passwd = abc
```

If this feature is eventually implemented, a benchmark between `rathole` and `ssh -D` will also be very appreciated.

**Comment by rapiz1** [comment]
Any plugin system will not be considered for rathole itself because the core has to keep neat and small.

Maybe when a web dashboard is available (will come in a separated package), the proposal can be considered
