### ISSUE TITLE
可不可以同一台服务器是发送端又是接收端

### ISSUE THREAD

**Issue by shijunti19** [rapiz1/rathole#189]
A2是封闭坏境的一台服务器（A2），他有个软件设置了80端口
A是封闭环境的另外一台服务器(A1)，他可以链接A2的80，然后我们需要链接到C这个外网服务器
C是外网服务器，我们对接外网用户，把数据传到A服务器进行保存
B链接A和C的中间坏境，封闭坏境不允许直连C所以通过B

现在A的80端口转发到B的2333端口
然后B的2333端口转发到C的2334端口
现在B需要运行2个cmd有点麻烦
A已经运行rathole 的发送端
C也运行了rathole 的接收端
但是B可不可以实现只需要一个命令实现接收和发送（我个人觉得这种场景应该很多，软件配置也支持这种）
可不可以这样config.toml
[client]
remote_addr = "B:2334"
[server]
bind_addr = "0.0.0.0:2333" 

然后运行
./rathole config.toml，不要加client和server
C可以正常接收到

**Comment by rapiz1** [comment]
B可以主动连接到A吗？如果可以，B可以只写一个client，local_addr写A



---Original---
From: ***@***.***&gt;
Sent at: 2022年9月8日(Thu) Noon1:51
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] 可不可以同一台服务器是发送端又是接收端 (Issue #189)




 
A服务器是封闭环境
 C是外网服务器
 B链接A和C的中间坏境
 
现在A的80端口转发到B的2333端口
 然后B的2333端口转发到C的2334端口
 现在B需要运行2个cmd有点麻烦
 
可不可以这样config.toml
 [client]
 remote_addr = "B:2334"
 [server]
 bind_addr = "0.0.0.0:2333"
 
然后运行
 ./rathole server.toml
 
C可以正常接收到

**Comment by shijunti19** [comment]
@rapiz1 A里的80端口也是其他封闭坏境的其他服务器。其实是4台服务器

**Comment by rapiz1** [comment]
你的使用场景比较复杂，需求是针对特定场景。但如果允许一个实例同时作为 server 和 client，可能会对一般的用户造成困惑，也会使架构上的概念变得模糊。因此我觉得不适合加入到软件本身的功能中。

但针对你的使用场景，为了方便运维，我觉得可以编写一个脚本来控制单节点上两个实例的启停。Linux 上通过 Bash 脚本很容易做到，我不太了解 Windows 的脚本能力，或许也可以使用 Python 调用 rathole 二进制。

**Comment by cdsjsz** [comment]
唔，其实我这边其实也有这样的需求🤣，目前靠糊了个bat解决

**Comment by aa51513** [comment]
我这边也有这样的需求，可惜了，只能手动启动2个进程了
