### ISSUE TITLE
Configurable Retry Connection Interval

### ISSUE THREAD

**Issue by andriykrefer** [rapiz1/rathole#197]
**Feature Proposed**
Allow to configure the retry interval by service (or by client), in the client toml configuration file.

When the client fails to connect to a server, it retries to connect in about 1 second. For some scenarios, depending on the number of clients and services other interval durations may be more appropriate

**Use Case**
I have a setup where 1 second is too often and it floods the network.

**Comment by rapiz1** [comment]
It actually uses an exponential backoff and the maximal interval is 1s. Do you mean the small initial interval floods the network?

**Comment by rapiz1** [comment]
Making the maximal retry interval configurable is easy. But I wonder if that actually solves your problem or we should do something else.

**Comment by rapiz1** [comment]
Option `retry_interval` is available in [v0.4.6](https://github.com/rapiz1/rathole/releases/tag/v0.4.6)

**Comment by andriykrefer** [comment]
Thank you very much for this implementation! It will surely solve my problem
