### ISSUE TITLE
Request to support wss protocol between client and server

### ISSUE THREAD

**Issue by aa51513** [rapiz1/rathole#198]
**Feature Proposed**

Already know that 3 protocols are currently supported, they are ["tcp", "tls", "noise"]

**Use Case**

Request to support wss protocol between client and server

**Comment by woOzZ2** [comment]
> #134的副本。

#134 所讨论的貌似不是客户端和服务端之间的传输协议。
需要被支持的是一下配置中
```
[client.transport] # The whole block is optional. Specify which transport to use
type = "tcp" # Optional. Possible values: ["tcp", "tls", "noise"]. Default: "tcp"
```
可以支持type = wss

**Comment by fernvenue** [comment]
That's exactly the same thing.

**Comment by woOzZ2** [comment]
> That's exactly the same thing.

hah，不好意思我口误了，我的意思是本issuse是新功能请求的意思，需要客户端和服务端使用wss通信酱紫。
现在最新版是无法配置type = wss的，这样的话有利于穿越CDN来部署

**Comment by fernvenue** [comment]
@woOzZ2 That's exactly what [#134](https://github.com/rapiz1/rathole/issues/134) is talking about, transport type means the protocol between client and server.

**Comment by woOzZ2** [comment]
> @woOzZ2 That's exactly what [#134](https://github.com/rapiz1/rathole/issues/134) is talking about, transport type means the protocol between client and server.

意思是目前支持wss作为传输协议吗？能配置type = wss？

**Comment by fernvenue** [comment]
@woOzZ2 Nope, just means that we don't need a duplicate issue about that, as you can see, this one closed as not planned instead of completed.
