### ISSUE TITLE
hot reload 在 docker 中是不是无效

### ISSUE THREAD

**Issue by xspio** [rapiz1/rathole#200]
运行 docker run -it --rm -v "path/to/config.toml:/app/config.toml" rathole --server /app/config.toml
然后修改 path/to/config.toml，但是并没有触发 reload，只有重启上面运行的 container 才生效
是哪里没有配置好吗？

**Comment by rapiz1** [comment]
可能和容器有关。Hot reload 是用操作系统的 inotify api 实现的。容器场景下overlayfs的变化可能无法感知



---Original---
From: ***@***.***&gt;
Sent at: 2022年11月2日(Wed) PM2:02
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [rapiz1/rathole] hot reload 在 docker 中是不是无效 (Issue #200)




 
运行 docker run -it --rm -v "path/to/config.toml:/app/config.toml" rathole --server /app/config.toml
 然后修改 path/to/config.toml，但是并没有触发 reload，只有重启上面运行的 container 才生效
 是哪里没有配置好吗？

**Comment by xspio** [comment]
以后会考虑在 rapiz1/rathole 镜像中加入 inotify-tools 吗

**Comment by rapiz1** [comment]
你确认过这样可以解决问题吗？我没有调查过。如果可以修复，可以加入镜像

**Comment by xspio** [comment]
尝试生成镜像来测试，不过报下面错误，怎么解决
```
Updating crates.io index
error: failed to select a version for the requirement `libgit2-sys = "^0.14.0"`
candidate versions found which didn't match: 0.13.2+1.4.2, 0.13.1+1.4.2, 0.13.0+1.4.1, ...
location searched: crates.io index
required by package `git2 v0.15.0`
```

**Comment by rapiz1** [comment]
https://github.com/rapiz1/rathole/blob/fix-dockerfile/Dockerfile 试试这个 Dockerfile

**Comment by xspio** [comment]
Dockerfile 可以了，不幸的是在镜像中加入 inotify-tools 并启动服务后还是无法 hot reload

**Comment by rapiz1** [comment]
应该是 docker 阻碍了 inotify 事件的传递
https://twitter.com/dr4goonis/status/950464956650094599?lang=en 可以尝试一下这里提到的解决方案，docker里volume指定一个目录。

**Comment by xspio** [comment]
按照上面说的，映射了整个文件夹，然后就生效了，太棒了
