### ISSUE TITLE
Docker Hub 镜像版本未同步更新

### ISSUE THREAD

**Issue by duriantang** [rapiz1/rathole#202]
**Describe the bug**

Docker Hub 上的镜像版本还是0.4.3的

**To Reproduce**
1. 打开 https://hub.docker.com/r/rapiz1/rathole/tags
2. latest version hash `9c287b02e4a4` 和 0.4.3 是一样的

![image](https://user-images.githubusercontent.com/381707/199876151-c78040cc-b431-49a7-ac2f-8c1d3da7b45d.png)

**Comment by rapiz1** [comment]
感谢反馈 已经更新了
