### ISSUE TITLE
Build for Linux/amd64 + musl

### ISSUE THREAD

**Issue by CompuRoot** [rapiz1/rathole#206]
**Feature Proposed**
There no build for Linux/amd64 architecture in releases 

**Use Case**
Utilize `rathole` capability on most used in the world architecture from prebuild binaries

**Comment by rapiz1** [comment]
[rathole-x86_64-unknown-linux-musl.zip](https://github.com/rapiz1/rathole/releases/download/v0.4.5/rathole-x86_64-unknown-linux-musl.zip) should suit you

**Comment by CompuRoot** [comment]
@rapiz1 Ooh, sorry, my apology, I didn't clicked on "show all 16 assets" :(
