### ISSUE TITLE
100% CPU usage on arm build

### ISSUE THREAD

**Issue by dharapvj** [rapiz1/rathole#211]
**Describe the bug**
If I run rathole as server on a t4g.small instance on AWS, the rathole process consumes 100% CPU on one core of the machine (50%).

**To Reproduce**

**Configuration**
Configuration used to reproduce the behavior:
1. Configuration of systemd service.
```
❯ cat /etc/systemd/system/rathole.service
[Unit]
Description=Rathole Server Service
After=network.target

[Service]
Type=simple
#DynamicUser=yes
Restart=on-failure
RestartSec=5s
ExecStart=/usr/local/bin/rathole -s /etc/rathole/rathole.toml
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
```
2. config file
```
❯ cat /etc/rathole/rathole.toml
# server.toml
[server]
bind_addr = "0.0.0.0:2333"
default_token = "SECRET_IS_SAFE"

[server.services.homelab_ssh]
bind_addr = "0.0.0.0:3332"

[server.services.homelab_rdp]
bind_addr = "0.0.0.0:3333"

[server.services.homelab_http]
bind_addr = "0.0.0.0:80"

[server.services.homelab_https]
bind_addr = "0.0.0.0:443"
```

**Logs**

No special logs to show 100% CPU usage

**Environment:**
 - OS: 
- `rathole --version` output: 
1. Rathole version
```
rathole
Build Timestamp:     2022-11-30T03:55:10.183120441Z
Build Version:       0.4.7
Commit SHA:          Some("ee5c7b4a770ef6c5b7ab5b21c1ee2c2f0a74f4f7")
Commit Date:         Some("2022-11-30T03:49:01Z")
Commit Branch:       Some("detached HEAD")
cargo Target Triple: arm-unknown-linux-musleabihf
cargo Profile:       release
cargo Features:      base64,client,default,hot_reload,noise,notify,server,snowstorm,tls,tokio_native_tls
```
I tried with `rathole-arm-unknown-linux-musleabi` as well. But it was exact same issue

- CPU architecture:
```
❯ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
❯ uname -a
Linux ip-172-31-22-66 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 17:01:09 UTC 2022 aarch64 aarch64
aarch64 GNU/Linux
```

**Comment by rapiz1** [comment]
Have you tried building from the source instead of using the release?

**Comment by guillaumecharbonnier** [comment]
I have found the same issue on Oracle cloud arm ampere. Building from source solved it as suggested.

**Comment by rapiz1** [comment]
I believe this has been resolved by upgrading upx

**Comment by dharapvj** [comment]
I tried this again today after a long time with latest 0.5.0 release and CPU usage is still at 100%

/reopen

**Comment by dharapvj** [comment]
> Have you tried building from the source instead of using the release?

I finally bit the bullet and built it on AWS gravitron machine and the built binary worked like a charm. No CPU slices to notice at all.
