### ISSUE TITLE
password protect public access

### ISSUE THREAD

**Issue by megablocks** [rapiz1/rathole#223]
**Feature Proposed**

when accessing public facing url:port, it would be good to password protect the access and if that can be configured in settings 
**Use Case**

For when a simple private web service is being forwarded to public port, need some kind of additional authentication

**Comment by fernvenue** [comment]
As you can see in [Out of Scope](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md), Rathole doesn't interface with the application layer protocol, so Rathole will not do that kind of things by itself, and I think Rathole shouldn't do. You can do that on your web application or web server, such as [NGINX](https://nginx.org/en/docs/http/ngx_http_auth_basic_module.html), [Traefik](https://doc.traefik.io/traefik/middlewares/http/basicauth/), [Caddy](https://caddyserver.com/docs/caddyfile/directives/basicauth), they all based on TCP and UDP, Rathole can handle that.
