### ISSUE TITLE
Problems with multiple clients using the same service

### ISSUE THREAD

**Issue by xcg340122** [rapiz1/rathole#229]
Like frp, clients can be dynamically identified by subdomain names. For example, multiple clients connect to a service without setting the service name on the server in advance.

**Comment by fernvenue** [comment]
As you can see in [Out of Scope](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md), Rathole will not to do Domain based forwarding or that kind of things by itself:

> Introducing these kind of features into `rathole` itself ultimately reinvent a nginx. Use nginx to do this and set rathole as the upstream. This method achieves better performance as well as flexibility.

So you should do that on your web application or web server.

**Comment by xcg340122** [comment]
For example, if A client with the service name A is connected to the server, if there is No configuration with the service name a, the message rathole::server: No such a service A is displayed.
Since A is dynamic, I want the user to access A. example.com, can access the corresponding machine a, access b. Example.com will give you access to machine b

**Comment by xcg340122** [comment]
For example, if A client with the service name A is connected to the server, if there is No configuration with the service name a, the message rathole::server: No such a service A is displayed.
Since A is dynamic, I want the user to access A. example.com, can access the corresponding machine a, access b. Example.com will give you access to machine b

**Comment by xcg340122** [comment]
> As you can see in [Out of Scope](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md), Rathole will not to do Domain based forwarding or that kind of things by itself:
> 
> > Introducing these kind of features into `rathole` itself ultimately reinvent a nginx. Use nginx to do this and set rathole as the upstream. This method achieves better performance as well as flexibility.
> 
> So you should do that on your web application or web server.

For example, if A client with the service name A is connected to the server, if there is No configuration with the service name a, the message rathole::server: No such a service A is displayed.
Since A is dynamic, I want the user to access A. example.com, can access the corresponding machine a, access b. Example.com will give you access to machine b

**Comment by fernvenue** [comment]
As I said above, Rathole will **NOT** to do that kind of things by itself, you can do that on your web application or web server.

**Comment by xcg340122** [comment]
> 

My demand is not multiple websites in a host, but multiple hosts corresponding to a server, hoping to find a different server through the subdomain name

**Comment by xcg340122** [comment]
> As I said above, Rathole will **NOT** to do that kind of things by itself, you can do that on your web application or web server.

Another way to ask: how do you support multiple clients using just one service

**Comment by xcg340122** [comment]
> As I said above, Rathole will **NOT** to do that kind of things by itself, you can do that on your web application or web server.

Here's the scenario: I add a service named nas1 to the service configuration, then I connect from machine A to the nas1 service, and now I have a new machine b that I want to use on machine b without changing the service configuration, because there may be many machines added later

**Comment by fernvenue** [comment]
You can set different service name for your client's services, in your example it will be like this:

- Server

```
[server.services.a]
...

[server.services.b]
...
```

- Client A

```
[client.services.a]
...
```

- Client B:

```
[client.services.b]
...
```

That's quite simple right? And if you wanna run multiple services but one systemd service configuration, you can use `@` symbol in name of your unit files, then you can run your each server or client like this:

```
systemctl start rathole@a
systemctl start rathole@b
systemctl start rathole@c
....
```

And we have examples here about that: examples here: https://github.com/rapiz1/rathole/tree/main/examples/systemd.

**Comment by xcg340122** [comment]
> 您可以为客户的服务设置不同的服务名称，在您的示例中它将是这样的：
> 
> * 服务器
> 
> ```
> [server.services.a]
> ...
> 
> [server.services.b]
> ...
> ```
> 
> * 客甲
> 
> ```
> [client.services.a]
> ...
> ```
> 
> * 客乙：
> 
> ```
> [client.services.b]
> ...
> ```
> 
> systemd服务但但服务但？如果你你运行但但服务但但但配置服务，你你服务服务`@`，你你可以可以可以在在在在在你你的的的单元文件文件的的中使用中中
> 
> ```
> systemctl start rathole@a
> systemctl start rathole@b
> systemctl start rathole@c
> ....
> ```
> 
> 我们在这里有关于这个的示例：此处示例：https://github.com/rapiz1/rathole/tree/main/examples/systemd。

[client.services.a] and [client.services.B] or [client.services.C] are both connected to [server.services.a]
The client name is not fixed in the configuration

**Comment by xcg340122** [comment]
> You can set different service name for your client's services, in your example it will be like this:
> 
> * Server
> 
> ```
> [server.services.a]
> ...
> 
> [server.services.b]
> ...
> ```
> 
> * Client A
> 
> ```
> [client.services.a]
> ...
> ```
> 
> * Client B:
> 
> ```
> [client.services.b]
> ...
> ```
> 
> That's quite simple right? And if you wanna run multiple services but one systemd service configuration, you can use `@` symbol in name of your unit files, then you can run your each server or client like this:
> 
> ```
> systemctl start rathole@a
> systemctl start rathole@b
> systemctl start rathole@c
> ....
> ```
> 
> And we have examples here about that: examples here: https://github.com/rapiz1/rathole/tree/main/examples/systemd.

What I mean is:[client.services.a] and [client.services.B] or [client.services.C] are both connected to [server.services.a]
The client name is not fixed in the configuration

**Comment by fernvenue** [comment]
And then how to make Rathole know which client should work here?

**Comment by xcg340122** [comment]
> And then how to make Rathole know which client should work here?

Yes, I hope to find the corresponding host through the domain name. I understand the way you just said through nginx, but my host is all over the country, I just don't want to modify the server configuration to dynamically add the client

**Comment by fernvenue** [comment]
See? We're now back to the beginning, you're still talking about domain based forwarding, and Rathole doesn't interface with the application layer protocol, so as I said above, Rathole will **NOT** to do Domain based forwarding or that kind of things by itself, you can find it in [Out of Scope](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md), duplicate questions: https://github.com/rapiz1/rathole/issues/179, https://github.com/rapiz1/rathole/issues/181. Do that on your web application or web server.

**Comment by xcg340122** [comment]
> See? We're now back to the beginning, you're still talking about domain based forwarding, and Rathole doesn't interface with the application layer protocol, so as I said above, Rathole will **NOT** to do Domain based forwarding or that kind of things by itself, you can find it in [Out of Scope](https://github.com/rapiz1/rathole/blob/main/docs/out-of-scope.md), duplicate questions: https://github.com/rapiz1/rathole/issues/179, https://github.com/rapiz1/rathole/issues/181. Do that on your web application or web server.

Well, then I'll have to replace it with frp...

**Comment by fernvenue** [comment]
Good luck.

**Comment by tecnicosya** [comment]
> 
Every client will have their own token?

**Comment by tecnicosya** [comment]
> Ref

Every client will have their own token?
