### ISSUE TITLE
能否支持配置多台服务器

### ISSUE THREAD

**Issue by wacdev** [rapiz1/rathole#239]
**Feature Proposed**
能否支持配置多台服务器

**Use Case**
为了防止单一服务器挂了连不上机器，我希望，同时映射一个端口到多台服务器

**Comment by fernvenue** [comment]
You can just use multiple rathole services to do that.

**Comment by fernvenue** [comment]
By the way, you can use `@` symbol in name of unit files so that you can run your each server or client like this:

```
systemctl start rathole@a
systemctl start rathole@b
systemctl start rathole@c
....
```

Actually we already have examples here: https://github.com/rapiz1/rathole/tree/main/examples/systemd.

**Comment by wacdev** [comment]
ok
