### ISSUE TITLE
support lower version of glibc for linux distros like CentOS 7

### ISSUE THREAD

**Issue by 5uy4n9** [rapiz1/rathole#240]
release build can't run on CentOS 7

./rathole
./rathole: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./rathole)

maybe try to build release on a lower glibc version base image like centos 7?

**Comment by fernvenue** [comment]
As you can see in [CentOS Lifecycle (EOL)](https://endoflife.software/operating-systems/linux/centos), CentOS 7 gonna end it's life soon, highly recommend you to use other distributions.

**Comment by rapiz1** [comment]
In this case you need to build your own.
