### ISSUE TITLE
可以增加一个socks5代理的feature吗？

### ISSUE THREAD

**Issue by reformc** [rapiz1/rathole#242]
就是服务端可以转发客户端的socks代理端口，用以访问客户端的内网。
我也是将客户端运行在较小的mips设备上，设备存储一共也只有5M，如果再另外启动一个socks服务，会增加设备负担。
而且socks代理功能写进一个feature，只要不在默认的feature里，并不会增加的编译体积。
我试过在你的代码基础上添加了一个线程用以运行socks代理，编译后体积只增加了几十K(用你的minimal编译并upx压缩后)，内存消耗几乎没有变化。

**Comment by fernvenue** [comment]
Duplicate of https://github.com/rapiz1/rathole/issues/241.

**Comment by aa51513** [comment]
I am also very much looking forward to this feature being implemented
