### ISSUE TITLE
32Bits Binary for Windows

### ISSUE THREAD

**Issue by tecnicosya** [rapiz1/rathole#255]
I want to get the binary 32bits

**Use Case**
This is useful in old machine will we cant update for compatibility software installed.

Thank you. Very nice software.

**Comment by tecnicosya** [comment]
I share the compiled version for Windows 32 Bits.
https://drive.google.com/file/d/16DyOU5QYY9UqjPAC8JOGVOCIAF6ngNCc/view?usp=share_link

**Comment by rapiz1** [comment]
Sorry, I'm not going to officially release binary for win32. Even Microsoft does not release 32-bit Windows anymore. People are dropping support for win32 and the toolchain is fragile. For example, GitHub Actions does not provide a 32-bit Windows runner for rathole to automatically build.

Glad to see you have it built and worked.
