### ISSUE TITLE
Compile 32Bit for windows

### ISSUE THREAD

**Issue by tecnicosya** [rapiz1/rathole#256]
Today I compile the Rathole for windows 32bits.
Compile and build without problems, run from cmd and show is "ok".
If I try to load a client or server (I dont need the server in 32bit but I test it, when start to write here.)config file show crash error.

Compile with this line:
cargo build --target i686-pc-windows-gnu

The error cmd log:
`.\rathole client.toml
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
regex parse error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1: (?x)
 2:                 ^(?P<global_level>(?i:trace|debug|info|warn|error|off|[0-5]))$ |
                                          ^
 3:                  #                 ^^^.
 4:                  #                     `note: we match log level names case-insensitively
 5:                 ^
 6:                 (?: # target name or span name
 7:                     (?P<target>[\w:-]+)|(?P<span>\[[^\]]*\])
 8:                 ){1,2}
 9:                 (?: # level or nothing
10:                     =(?P<level>(?i:trace|debug|info|warn|error|off|[0-5]))?
11:                      #          ^^^.
12:                      #              `note: we match log level names case-insensitively
13:                 )?
14:                 $
15:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: Unicode-aware case insensitivity matching is not available (make sure the unicode-case feature is enabled)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
)', C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tracing-subscriber-0.2.25\src\filter\env\directive.rs:167:14
stack backtrace:
   0:  0x184b69d - core::fmt::write::ha09124839041e197
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\fmt/mod.rs:1232:17
   1:  0x17eda14 - std::io::Write::write_fmt::h6fdb4d4b96ed407e
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\io/mod.rs:1684:15
   2:  0x17f73f0 - std::sys_common::backtrace::_print::h7eeb512de866f086
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common/backtrace.rs:47:5
   3:  0x17f73f0 - std::sys_common::backtrace::print::h5b5962ee325a0079
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common/backtrace.rs:34:9
   4:  0x17f9cb5 - std::panicking::default_hook::{{closure}}::hfdc9540043d22016
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:271:22
   5:  0x17f9a29 - std::panicking::default_hook::h875c9a9b5a7fdb54
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:290:9
   6:  0x17fa483 - std::panicking::rust_panic_with_hook::h27da40ce2c12186e
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:692:13
   7:  0x17fa276 - std::panicking::begin_panic_handler::{{closure}}::h932a4d7abd031c92
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:583:13
   8:  0x17f7ed8 - std::sys_common::backtrace::__rust_end_short_backtrace::h5799d81708b3a3e5
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common/backtrace.rs:150:18   9:  0x17f9fd5 - rust_begin_unwind
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:579:5
  10:  0x1847c0d - core::panicking::panic_fmt::hfe28eda85ffaa79b
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src/panicking.rs:64:14
  11:  0x18480b9 - core::result::unwrap_failed::h539919d58c9790f5
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src/result.rs:1750:5
  12:   0xe24a55 - core::result::Result<T,E>::unwrap::h97104c359558b629
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src/result.rs:1090:23
  13:   0xdd1696 - <<tracing_subscriber::filter::env::directive::Directive as core::str::traits::FromStr>::from_str::DIRECTIVE_RE as core::ops::deref::Deref>::deref::__static_ref_initialize::ha630a2033e3599da
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tracing-subscriber-0.2.25\src\filter\env\directive.rs:150:46
  14:   0xdd1696 - core::ops::function::FnOnce::call_once::hdb785fc4731c6df5
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\ops/function.rs:250:5
  15:   0xe2d826 - lazy_static::lazy::Lazy<T>::get::{{closure}}::h7ddb895bbce8a1be
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\lazy_static-1.4.0\src\inline_lazy.rs:31:29
  16:   0xdfc75a - std::sync::once::Once::call_once::{{closure}}::hd314ea4cc58ce96d
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\std\src\sync/once.rs:149:41
  17:  0x180bc3e - std::sys_common::once::queue::Once::call::haa204092ffe65b4e
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\sys_common\once/queue.rs:183:21
  18:   0xdfc561 - std::sync::once::Once::call_once::hb5adce57623acccb
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\std\src\sync/once.rs:149:9
  19:   0xdc63c7 - lazy_static::lazy::Lazy<T>::get::h09722a2b4506da1b
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\lazy_static-1.4.0\src\inline_lazy.rs:30:9
  20:   0xdc63c7 - <<tracing_subscriber::filter::env::directive::Directive as core::str::traits::FromStr>::from_str::DIRECTIVE_RE as core::ops::deref::Deref>::deref::__stability::h1e75b1dfb46c08fc
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\lazy_static-1.4.0\src\lib.rs:142:21
  21:   0xdc63c7 - <<tracing_subscriber::filter::env::directive::Directive as core::str::traits::FromStr>::from_str::DIRECTIVE_RE as core::ops::deref::Deref>::deref::hd83f36b1279633de
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\lazy_static-1.4.0\src\lib.rs:144:17
  22:   0xdc3d4f - <tracing_subscriber::filter::env::directive::Directive as core::str::traits::FromStr>::from_str::h5761bf209e302700
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tracing-subscriber-0.2.25\src\filter\env\directive.rs:185:20
  23:   0xdd53ca - core::str::<impl str>::parse::h29a08e28c313b80a
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\str/mod.rs:2353:9
  24:   0xc7e410 - tracing_subscriber::filter::env::EnvFilter::new::{{closure}}::he7f49c8b0e0b8975
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tracing-subscriber-0.2.25\src\filter\env\mod.rs:156:72
  25:   0xc7e57a - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h411f50a883086a7a
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\ops/function.rs:298:13
  26:   0xda9b82 - core::iter::traits::iterator::Iterator::find_map::check::{{closure}}::h3d1e0df8751c409a
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\iter\traits/iterator.rs:2795:32
  27:   0xb92d78 - core::iter::traits::iterator::Iterator::try_fold::hf563fba42356fab2
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\iter\traits/iterator.rs:2299:21
  28:   0xb92c5e - core::iter::traits::iterator::Iterator::find_map::h074ebc3851ff4ae4
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\iter\traits/iterator.rs:2801:9
  29:   0xced511 - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h1babdc2bcd0ce03e
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\iter\adapters/filter_map.rs:61:9
  30:   0xdab207 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h9d3100babb2e3b87
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\alloc\src\vec/spec_from_iter_nested.rs:26:32
  31:   0xdac2dd - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h1111f41a732dc2b1
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\alloc\src\vec/spec_from_iter.rs:33:9
  32:   0xdac263 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h5f12da0222c2e988
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\alloc\src\vec/mod.rs:2724:9
  33:   0xced58d - core::iter::traits::iterator::Iterator::collect::h3b1277f048fe5a5e
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\iter\traits/iterator.rs:1891:9
  34:   0xc7d199 - tracing_subscriber::filter::env::EnvFilter::from_directives::h9b2b714ea85eec47
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tracing-subscriber-0.2.25\src\filter\env\mod.rs:253:34
  35:   0xc7e3ab - tracing_subscriber::filter::env::EnvFilter::new::h215a2aca354ab7de
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tracing-subscriber-0.2.25\src\filter\env\mod.rs:163:9
  36:   0xc7e5ba - <tracing_subscriber::filter::env::EnvFilter as core::convert::From<S>>::from::hb2385beb089ed562
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tracing-subscriber-0.2.25\src\filter\env\mod.rs:499:9
  37:   0xced4cf - rathole::main::{{closure}}::{{closure}}::hbf1ffaa9a8366add
                       at C:\Users\home\Documents\Desarrollo\Tunnel Remoto -Teletrabajo\Codigo\rathole-0.4.7\rathole-0.4.7\src\main.rs:38:70
  38:   0xcda0c8 - core::result::Result<T,E>::unwrap_or_else::heb0ce253d217b323
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src/result.rs:1465:23
  39:   0xced062 - rathole::main::{{closure}}::hf3a01a0a1f9d837d
                       at C:\Users\home\Documents\Desarrollo\Tunnel Remoto -Teletrabajo\Codigo\rathole-0.4.7\rathole-0.4.7\src\main.rs:38:17
  40:   0xd0eaa9 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::he1d248fda895140f
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tokio-1.28.1\src\runtime\park.rs:283:63
  41:   0xd0e77e - tokio::runtime::coop::with_budget::h05a27833a6dce86d
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tokio-1.28.1\src\runtime\coop.rs:107:5
  42:   0xd0e77e - tokio::runtime::coop::budget::hbd8f9e6a37c0f46d
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tokio-1.28.1\src\runtime\coop.rs:73:5
  43:   0xd0e77e - tokio::runtime::park::CachedParkThread::block_on::h207d298958c24ca0
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tokio-1.28.1\src\runtime\park.rs:283:31
  44:   0xbaf4d6 - tokio::runtime::context::BlockingRegionGuard::block_on::hb2231f19435590af
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tokio-1.28.1\src\runtime\context.rs:315:13
  45:   0xd52646 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h7eddaccc740af4dd
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tokio-1.28.1\src\runtime\scheduler\multi_thread\mod.rs:66:9
  46:   0xd3a919 - tokio::runtime::runtime::Runtime::block_on::h32c6f806ae44c012
                       at C:\Users\home\.cargo\registry\src\github.com-1285ae84e5963aae\tokio-1.28.1\src\runtime\runtime.rs:304:45
  47:   0xda9ff6 - rathole::main::he174bc0b05b8793e
                       at C:\Users\home\Documents\Desarrollo\Tunnel Remoto -Teletrabajo\Codigo\rathole-0.4.7\rathole-0.4.7\src\main.rs:25:5
  48:   0xd14ad9 - core::ops::function::FnOnce::call_once::h7a0ae26a88dcf9d4
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\ops/function.rs:250:5
  49:   0xc82791 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd39ba981e20b4e6b
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\std\src\sys_common/backtrace.rs:134:18  50:   0xc80ab3 - std::rt::lang_start::{{closure}}::h4f89a0a857113006
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\std\src/rt.rs:166:18
  51:  0x17e093e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h024834639c8b731e
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\ops/function.rs:287:13
  52:  0x17e093e - std::panicking::try::do_call::h19a36e2bc75ca16d
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:487:40
  53:  0x17e093e - std::panicking::try::h1608b2ac373e2b1e
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:451:19
  54:  0x17e093e - std::panic::catch_unwind::hf8a0c7e5f9abc2be
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panic.rs:140:14
  55:  0x17e093e - std::rt::lang_start_internal::{{closure}}::h373f5d295ba4b5fd
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/rt.rs:148:48
  56:  0x17e093e - std::panicking::try::do_call::ha6622600d9bd188b
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:487:40
  57:  0x17e093e - std::panicking::try::h6ab68beb830338f8
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panicking.rs:451:19
  58:  0x17e093e - std::panic::catch_unwind::he6e7daa27ff5aa30
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/panic.rs:140:14
  59:  0x17e093e - std::rt::lang_start_internal::hd465fe35c487fab3
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src/rt.rs:148:20
  60:   0xc80a8b - std::rt::lang_start::hbecbb3c01799524a
                       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\std\src/rt.rs:165:17
  61:   0xdaa06e - _main
  62:   0xb912f0 - __tmainCRTStartup
                       at C:\M\B\src\build-MINGW32\C:/M/B/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:272:15
  63: 0x76917d59 - <unknown>
  64: 0x7707b74b - <unknown>
  65: 0x7707b6cf - <unknown>`

Rust Toolchain:
`rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\home\.rustup

installed toolchains
--------------------

stable-i686-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-i686-pc-windows-gnu (default)
rustc 1.69.0 (84c898d65 2023-04-16)`

**Comment by tecnicosya** [comment]
I found other tool called bore and have windows 32 bit binary, but is Rathole is more faster for what I need.
Anybody will help me to build windows 32bit excutable?

**Comment by rapiz1** [comment]
Can you compile with the `main` branch?

**Comment by tecnicosya** [comment]
> Can you compile with the `main` branch?

I'm not expert, just download the source code where are the releases and with lasted. 
A lot of configurations on my pc. Install rust, gcc, search tutorials to compile rust 😅😅😅.

**Comment by rapiz1** [comment]
![image](https://github.com/rapiz1/rathole/assets/20105061/0c2f4038-260c-4723-b158-8423026d4330)
Here you can download the main branch, which contains unreleased changes.

**Comment by tecnicosya** [comment]
> ![image](https://user-images.githubusercontent.com/20105061/241125509-0c2f4038-260c-4723-b158-8423026d4330.png) Here you can download the main branch, which contains unreleased changes.

Here we go again!

**Comment by tecnicosya** [comment]
> ![image](https://user-images.githubusercontent.com/20105061/241125509-0c2f4038-260c-4723-b158-8423026d4330.png) Here you can download the main branch, which contains unreleased changes.

Hey! Thank you! Now is working on Windows 7 32bits.

**Comment by rapiz1** [comment]
Thanks for your feedback. I will make a release soon.

**Comment by rapiz1** [comment]
Fixed in https://github.com/rapiz1/rathole/releases/tag/v0.4.8
