### ISSUE TITLE
How can I list the rules on linux?

### ISSUE THREAD

**Issue by tecnicosya** [rapiz1/rathole#257]
First thank you for this nice software.
I want to know how can I see the rules in the server side, to apply IP Allow or Disallow. 
Just to apply for every rule created on rathole.

**Comment by rapiz1** [comment]
Do you mean an IP whitelist/blacklist for a specific port? You're probably looking for that in firewall configurations, not rathole

**Comment by tecnicosya** [comment]
> 

Yes I want it, but how rathole create the routes and how can I list?
I try with iptables -S and others but I'm a noob

**Comment by rapiz1** [comment]
rathole does not create routes. Just configure your firewall for the port rathole is listening
