### ISSUE TITLE
Microsoft Defender marked the app as Trojan

### ISSUE THREAD

**Issue by navanshu** [rapiz1/rathole#258]
Rathole executable downloaded from release page, kindly verify the issue https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.H!ml&threatid=2147814524

![Screenshot 2023-05-27 162000](https://github.com/rapiz1/rathole/assets/7664426/f24ab0f6-7b1e-4e76-8203-17b024f9d08d)

**Comment by rapiz1** [comment]
The binary is built from source by GitHub Actions. This is a false positive. If you're concerned, you can build your own binary.

**Comment by rohanjoshirj** [comment]
Same here ... Shows in the latest version only?
