### ISSUE TITLE
公开的端口不想谁都可以访问怎么设置？

### ISSUE THREAD

**Issue by 107295472** [rapiz1/rathole#274]
[server.services.my_nas_ssh]
token = "use_a_secret_that_only_you_know" # Token that is used to authenticate the client for the service. Change to a arbitrary value.
bind_addr = "0.0.0.0:5202" # `5202`   这个不想谁都可以访问，现在我用其他机器访问外网ip:5202就连上了

**Comment by fernvenue** [comment]
Use your system's iptables/firewall to do that, rathole doesn't care about these kind of things.
