### ISSUE TITLE
-ash: ./rathole: not found

### ISSUE THREAD

**Issue by devksks** [rapiz1/rathole#279]
<img width="213" alt="image" src="https://github.com/rapiz1/rathole/assets/91334244/8e1b5076-4f75-44cc-955a-78b0a3f065b3">
用的小米路由器，frps可以使用，是不是缺少依赖？

**Comment by fernvenue** [comment]
Could you please try `ls` and show the output?

**Comment by devksks** [comment]
> Could you please try `ls` and show the output?

<img width="179" alt="image" src="https://github.com/rapiz1/rathole/assets/91334244/d71d768f-80ac-4928-9307-3bb4fd5c3186">

**Comment by fernvenue** [comment]
No, I mean `ls` not `ls ./rathole`.

**Comment by devksks** [comment]
> No, I mean `ls` not `ls ./rathole`.

<img width="354" alt="image" src="https://github.com/rapiz1/rathole/assets/91334244/70f117a3-b71a-425e-94e9-7ce6b2a7cf2a">

**Comment by fernvenue** [comment]
I see, and I think this is a duplicate issue of https://github.com/rapiz1/rathole/issues/164, so you may wanna check there.
