### ISSUE TITLE
能否支持proxy protocol协议，实现获取real ip

### ISSUE THREAD

**Issue by SAENE** [rapiz1/rathole#295]
**Feature Proposed**
能否支持proxy protocol协议，实现获取real ip

**Use Case**
虽然能套个nginx实现获取用户real ip，但是整体性能变差了，而且延迟也大大增加了。
像雷池waf这种web防火墙，部分封禁ip功能需要获得真实ip，不然没有效果

**Comment by fernvenue** [comment]
Duplicate of https://github.com/rapiz1/rathole/issues/142, see also https://github.com/rapiz1/rathole/issues/221 https://github.com/rapiz1/rathole/issues/150 https://github.com/rapiz1/rathole/issues/176 for this feature.
