### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rapiz1** [rapiz1/rathole#32]
Lots of features and optimization have been introduced since v0.1.0. Documentations are needed to indicate that, including:
- [x] The security model and the encryption
- [x] Hot-reloading
- [x] More benchmark about various use cases and memory https://github.com/rapiz1/rathole/issues/21

**Comment by shirshak55** [comment]
As readme is getting more and more maybe we should create rathole organization and make a page so that we can use 

rathole.github.io for various other things like docs, introduction, etc.

**Comment by shirshak55** [comment]
I would recommend https://github.com/aaranxu/adidoks demo: https://adidoks.org/docs/getting-started/introduction/ for documentation. 

Also, we can easily host for free using GitHub page it might be better in long term?

**Comment by shirshak55** [comment]
@rapiz1 let me know if you are okay with it I can set up repo for this :)
