### ISSUE TITLE
windows service not support

### ISSUE THREAD

**Issue by lordnic99** [rapiz1/rathole#356]
**Describe the bug**

I'm using nssm for running the rathole in background, I got this error.
![image](https://github.com/rapiz1/rathole/assets/96934829/5530b8e5-caf3-4cc4-813e-a1634de4ac0c)

**To Reproduce**
1. Install rathole on the background with nssm
2. Start the service with nssm start {SERVICE_NAME}, got the error like the picture.

**Configuration**
Configuration used to reproduce the behavior:
![image](https://github.com/rapiz1/rathole/assets/96934829/b6369d50-7faf-4fb2-b68e-474a0c30d54f)

**Logs**

There is no log cause windows service not showing anything when get failed
**Environment:**
 - OS: Windows 11, Windows Server 2012
- `rathole --version` output: 
rathole
Build Timestamp:     2023-10-01T10:01:42.9022838Z
Build Version:       0.5.0
Commit SHA:          Some("ebb764ae53d7ffe4fcb45f83f7563bec5c74199d")
Commit Date:         Some("2023-10-01T09:55:18Z")
Commit Branch:       Some("detached HEAD")
cargo Target Triple: x86_64-pc-windows-msvc
cargo Profile:       release
cargo Features:      base64,client,default,futures_core,futures_sink,hot_reload,noise,notify,server,snowstorm,tls,tokio_native_tls,tokio_tungstenite,tokio_util,websocket

- CPU architecture: amd64
- rustc version: I'm using release version.

**Comment by fernvenue** [comment]
You need to specify the ` client.toml` to the argument part, not the path.

**Comment by lordnic99** [comment]
> You need to specify the ` client.toml` to the argument part, not the path.

![image](https://github.com/rapiz1/rathole/assets/96934829/afeafedd-cd8d-472d-a2a1-5a60bfc2ece1)
![image](https://github.com/rapiz1/rathole/assets/96934829/2d00d4db-c43f-4937-b851-59abbd092b80)

I have updated to this, but still same result.

**Comment by ZhiShengYuan** [comment]
> > You need to specify the ` client.toml` to the argument part, not the path.
> 
> ![image](https://private-user-images.githubusercontent.com/96934829/324186919-afeafedd-cd8d-472d-a2a1-5a60bfc2ece1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjcxNjksIm5iZiI6MTcxMzYyNjg2OSwicGF0aCI6Ii85NjkzNDgyOS8zMjQxODY5MTktYWZlYWZlZGQtY2Q4ZC00NzJkLWEyYTEtNWE2MGJmYzJlY2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE1Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YWJjMzBkNzhjYTYwOWFhMWNjNzc3N2UxNWVlZjgyOTZlMjg5OWI5NmFhNDZkNDIxMDVhZmY0MDFkNDFmZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KTIzy8zCQxqs_16mMukYcus2CT2IT9Ri2voHjJ8-eXk) ![image](https://private-user-images.githubusercontent.com/96934829/324186950-2d00d4db-c43f-4937-b851-59abbd092b80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjcxNjksIm5iZiI6MTcxMzYyNjg2OSwicGF0aCI6Ii85NjkzNDgyOS8zMjQxODY5NTAtMmQwMGQ0ZGItYzQzZi00OTM3LWI4NTEtNTlhYmJkMDkyYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE1Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NmRjY2Q3ZTYyOTM4NmVlNTcwNmMzMGYwZGJiMjJmNjVhMjVmYzM2ZjU5MGZhNDVjNDZkYzQ5YzFiMDA0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w7u8a3K_OTI2oQkqwSTW3ZTQnKywvswppEHKXZdlSdI)
> 
> I have updated to this, but still same result.


Reading the NSSM manual sounds like a good step. It's always helpful to refer to the official documentation for detailed information. Additionally, reaching out to someone familiar with this software could provide valuable insights or tips. Let's explore both avenues to resolve this issue efficiently.

**Comment by lordnic99** [comment]
Fixed by write a C++ for calling rathole, instead of calling it directly from nssm.

`#include <iostream>
#include <string>
#include <windows.h>

int main() {
  std::string command_line = "C:\\HoangVPN\\rathole.exe C:\\HoangVPN\\client.toml";

  STARTUPINFO si;
  memset(&si, 0, sizeof(si));
  si.cb = sizeof(si);

  PROCESS_INFORMATION pi;
  memset(&pi, 0, sizeof(pi));

  if (!CreateProcess(NULL, const_cast<char*>(command_line.c_str()), NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi)) {
    std::cerr << "Error creating process: " << GetLastError() << std::endl;
    return 1;
  }

  WaitForSingleObject(pi.hProcess, INFINITE);

  CloseHandle(pi.hProcess);
  CloseHandle(pi.hThread);

  return 0;
}`

![image](https://github.com/rapiz1/rathole/assets/96934829/96637d4c-adae-4a67-8d14-12c68988957c)

**Comment by fernvenue** [comment]
As I said above, you actually just need:

> You need to specify the ` client.toml` to the argument part, not the path.

Like this:

![image](https://github.com/rapiz1/rathole/assets/84565547/fd2a2118-74ed-4ee6-bee8-1a4532154c49)

Is that hard to understand? And just like @ZhiShengYuan said, try to read the documentation first, don't assume you found a bug or something.

**Comment by lordnic99** [comment]
> As I said above, you actually just need:
> 
> > You need to specify the ` client.toml` to the argument part, not the path.
> 
> Like this:
> 
> ![image](https://private-user-images.githubusercontent.com/84565547/324220243-fd2a2118-74ed-4ee6-bee8-1a4532154c49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2Njg3NjYsIm5iZiI6MTcxMzY2ODQ2NiwicGF0aCI6Ii84NDU2NTU0Ny8zMjQyMjAyNDMtZmQyYTIxMTgtNzRlZC00ZWU2LWJlZTgtMWE0NTMyMTU0YzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAzMDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0M2EzMWZmNTg5ZWVhNzkwZmUzZGVmNWU0NDhlMDcxZDZkMGU4MDk5YzY1YTNlMWQyZDQ0ZTliNDkwOTliZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZHktKNm2vX8yRpKG0Oa2Aio7s-L9YRE_FAoc4VSPaDA)
> 
> Is that hard to understand? And just like @ZhiShengYuan said, try to read the documentation first, don't assume you found a bug or something.

Thanks, it works like charm.
