### ISSUE TITLE
Connection dies after logging out from ssh

### ISSUE THREAD

**Issue by shootie22** [rapiz1/rathole#358]
**Describe the bug**
Everything works as expected as long as I'm logged into the client machine through ssh. Once I log out, the connection dies.

**To Reproduce**
1. Create a server
2. Create a client
3. Make sure the connection works
4. Log out of client ssh
5. Wait a few seconds (~10-20s)
6. Notice the connection died

**Configuration**
I used the basic example. I also tried using the heartbeat and keepalive options, but to no avail.

**Logs**
I cannot find logs, it would be nice if someone can point me into the right direction to find them.

**Environment:**
 - OS: Ubuntu 22.04 LTS
- `rathole --version` output:
```rathole 
Build Timestamp:     2023-10-01T09:58:53.343888748Z
Build Version:       0.5.0
Commit SHA:          Some("ebb764ae53d7ffe4fcb45f83f7563bec5c74199d")
Commit Date:         Some("2023-10-01T09:55:18Z")
Commit Branch:       Some("detached HEAD")
cargo Target Triple: x86_64-unknown-linux-gnu
cargo Profile:       release
cargo Features:      base64,client,default,futures_core,futures_sink,hot_reload,noise,notify,server,snowstorm,tls,tokio_native_tls,tokio_tungstenite,tokio_util,websocket```
- CPU architecture: x64

**Comment by shootie22** [comment]
of course I realized what was wrong within minutes of creating the issue.  
  
if you create your client as a non-root service, it will die when your session dies, a.k.a. when you log out.  
I switched the service to be a system service instead of a user service and now it stays alive.

**Comment by jtmusselman** [comment]
@shootie22 you can use loginctl to have a systemd service as a user https://wiki.archlinux.org/title/Systemd/User#Automatic_start-up_of_systemd_user_instances
