### ISSUE TITLE
Detected as Virus

### ISSUE THREAD

**Issue by distributev** [rapiz1/rathole#397]
![image](https://github.com/user-attachments/assets/88788a66-8e18-452b-a2b8-04e62e4b5c68)

**Comment by distributev** [comment]
![image](https://github.com/user-attachments/assets/30bde2c3-26d9-4990-970c-b72e8877fcac)

**Comment by rapiz1** [comment]
use at your own risk

**Comment by rapiz1** [comment]
this has been brought up over and over again. search the issues if you want

**Comment by distributev** [comment]
Alternative 

https://github.com/ekzhang/bore

and many others

https://github.com/anderspitman/awesome-tunneling
