### ISSUE TITLE
client connect server through an proxy

### ISSUE THREAD

**Issue by FunnyWolf** [rapiz1/rathole#56]
sometime the clinet cannot connect  server  direct,client  need to  connect  server  by  an  proxy (Usually HTTP proxy)

**Comment by rapiz1** [comment]
Yes. It will be useful if HTTP_PROXY is supported.

In fact, there's another issue about SOCKS support planned to land in the next minor release https://github.com/rapiz1/rathole/issues/35

I will keep this issue open to track the progress of HTTP_PROXY

**Comment by FunnyWolf** [comment]
> I will keep this issue open to track the progress of HTTP_PROXY. What do you think?

awesome~

**Comment by rapiz1** [comment]
track in https://github.com/rapiz1/rathole/issues/56
