### ISSUE TITLE
Hot reloading breaks when changing the service name

### ISSUE THREAD

**Issue by clarkmcc** [rapiz1/rathole#67]
If I change the service name, the client does not know to unregister the previous service, and re-register a new service under the same name. Getting the following error:

```
Jan 05 07:06:15.562 ERROR new{service=foo1}: rathole::client: Failed to run the control channel

Caused by:
    0: Authentication failed: foo1
    1: Service not exist

Retry in 1s...
```

**Comment by rapiz1** [comment]
Can you elaborate on how to reproduce this? I can't reproduce it on my machine.

Note that you must both change the name on the server side and the client side.

**Comment by rapiz1** [comment]
Thanks! I've confirmed it. This only happens when both `[client]` and `[server]` is present. Working on a fix.

**Comment by clarkmcc** [comment]
Awesome! Thank you very much!

**Comment by rapiz1** [comment]
A fix has been merged 🎉
