### ISSUE TITLE
Add support for Arm

### ISSUE THREAD

**Issue by zytanic** [rapiz1/rathole#69]

**Comment by rapiz1** [comment]
@phyng That's not easy to set up :) Since Github Action doesn't provide M1 runner, we have to do cross build. And CI uses [cross](https://github.com/rust-embedded/cross) to cross build and M1 is not supported for now.

**Comment by rapiz1** [comment]
> The aarch64-unknown-linux-musl does not work on my Pi Zero. I expect that the aarch64-unknown-linux-musl is compiled for ARMv7.
ARMv7 is actually 32bits :)

Anyway I'm glad to provide releases for more architectures.
@jasonlearst Can you checkout [rustc Platform Support](https://doc.rust-lang.org/stable/rustc/platform-support.html) to pick ARM ones that you think will be very useful for you and other users? I don't know much about ARM and there are so many targets 😅

**Comment by zytanic** [comment]
I tried to run it on my raspberry PI 3

**Comment by jasonlearst** [comment]
I did some reading and found that these targets are needed to support the current Raspberry Pis

- arm-unknown-linux-gnueabihf
- arm-unknown-linux-musleabihf
- armv7-unknown-linux-gnueabihf
- armv7-unknown-linux-musleabihf

Source: https://piers.rocks/docker/containers/raspberry/pi/rust/cross/compile/compilation/2018/12/16/rust-compilation-for-raspberry-pi.html

**Comment by rapiz1** [comment]
@jasonlearst Thank you very much! I will try to include these targets

**Comment by rapiz1** [comment]
I built some binaries in a ci test repo. Can you try this out? https://github.com/yssjglg/rathole/releases/tag/v0.3.2 @jasonlearst @zytanic

**Comment by phyng** [comment]
@rapiz1 
It can be compiled successfully on Apple M1, I have no problem 😄 
```
➜  rathole git:(main) file target/release/rathole    
target/release/rathole: Mach-O 64-bit executable arm64

```

**Comment by zytanic** [comment]
Works on the raspberry pi now

**Comment by rapiz1** [comment]
> Works on the raspberry pi now

Glad to hear that :)

**Comment by jasonlearst** [comment]
Thanks for the new binaries!

Using rathole-armv7-unknown-linux-musleabihf.zip on my Pi 4 and rathole-arm-unknown-linux-musleabihf.zip on my Pi Zero I am able to create a working rathole connection.

**Comment by tonyho** [comment]
@rapiz1 The size of  the armv7 version is about 2MB, this is too big for embedded devices. Any plan to reduce the size in following release?

**Comment by rapiz1** [comment]
> Any plan to reduce the size in following release?

Currently binaries of some platforms(including arm) are not stripped. https://github.com/rapiz1/rathole/issues/71 tracks the cross-platform strip effort.

But you can always strip manually, if you have the arm toolchain. See [strip](https://man7.org/linux/man-pages/man1/strip.1.html). This may reduce the binary by ~1MiB.

And if that's not enough, you can build `rathole` without some features. See the [build guide](https://github.com/rapiz1/rathole/blob/main/docs/build-guide.md). If you want certain feature combinations to be build with each release, you can give some feedback under https://github.com/rapiz1/rathole/issues/70

**Comment by tonyho** [comment]
> > Any plan to reduce the size in following release?
> 
> Currently binaries of some platforms(including arm) are not stripped. #71 tracks the cross-platform strip effort.
> 
> But you can always strip manually, if you have the arm toolchain. See [strip](https://man7.org/linux/man-pages/man1/strip.1.html). This may reduce the binary by ~1MiB.
> 
> And if that's not enough, you can build `rathole` without some features. See the [build guide](https://github.com/rapiz1/rathole/blob/main/docs/build-guide.md). If you want certain feature combinations to be build with each release, you can give some feedback under #70

It has been stripped already for the armv7 elf (rathole-armv7-unknown-linux-musleabihf.zip):
```
file rathole
rathole: ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, stripped

$ arm-linux-gnueabihf-strip -S rathole.armv7 
arm-linux-gnueabihf-strip: error: the input file 'rathole.armv7' has no sections


$ du -sh rathole
2.1M	rathole
```

**Comment by rapiz1** [comment]
@tonyho Oh. It has been already compressed by `upx` so the `strip` cannot find the sections that it needs to strip. You can checkout the [strip status here](https://github.com/rapiz1/rathole/runs/4727869372?check_suite_focus=true) to know if a binary is successfully stripped.

In this case, you need to build a binary by yourself, then run strip and upx :)

**Comment by rapiz1** [comment]
It seems like nobody requests for more ARM binaries of other different targets. Closed. Feel free to open an issue if anyone has other questions.
