### ISSUE TITLE
能不需要客户端吗？只想单纯的端口转发，不需要token

### ISSUE THREAD

**Issue by gcxfd** [rapiz1/rathole#86]
如题

**Comment by rapiz1** [comment]
> 能不需要客户端吗？

我没有理解你的意思。如果希望配置能够在服务端统一管理配置方便，可以等一下 dashboard，在开发计划中。

> 只想单纯的端口转发，不需要 token 

不需要 Token 的话任意外网访问者都可以打开你的端口并转发任意流量，这是非常不安全的。

**Comment by gcxfd** [comment]
比如我只想把一个内网的80和443端口映射到公网，任意人都可以访问，用frp就可以做，但是用rathole不行

**Comment by gcxfd** [comment]
我理解错了。。。
